name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to use for UI tests'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
          - edge

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run API tests
        run: dotnet test tests/MyProject.ApiTests/MyProject.ApiTests.csproj --no-build --logger "trx;LogFileName=api-tests.trx"

      - name: Publish API Test Results
        uses: actions/upload-artifact@v2
        with:
          name: api-test-results
          path: '**/TestResults/api-tests.trx'

  ui-tests:
    runs-on: ubuntu-latest
    needs: api-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run UI tests
        run: |
          BROWSER=${{ github.event.inputs.browser }}
          if [ -z "$BROWSER" ]; then
            BROWSER='chrome'
          fi
          echo "Running UI tests in $BROWSER"
          dotnet test tests/MyProject.UiTests/MyProject.UiTests.csproj --no-build --logger "trx;LogFileName=ui-tests.trx"

      - name: Publish UI Test Results
        uses: actions/upload-artifact@v2
        with:
          name: ui-test-results
          path: '**/TestResults/ui-tests.trx'

      - name: Publish UI Test Screenshots
        uses: actions/upload-artifact@v2
        with:
          name: ui-test-screenshots
          path: '**/screenshots/*'
